#!/bin/bash
files=("$1"*.vst3)
idx=0
for file in "${files[@]}"
do
./testvst3.exe "${file}"
let idx++
done
files2=("$1"*/*.vst3)
idx2=0
for file2 in "${files2[@]}"
do
./testvst3.exe "${file2}"
let idx2++
done
files3=("$1"*/*/*.vst3)
idx3=0
for file3 in "${files3[@]}"
do
./testvst3.exe "${file3}"
let idx3++
done
files4=("$1"*/*/*/*.vst3)
idx4=0
for file4 in "${files4[@]}"
do
./testvst3.exe "${file4}"
let idx4++
done
files5=("$1"*/*/*/*/*.vst3)
idx5=0
for file5 in "${files5[@]}"
do
./testvst3.exe "${file5}"
let idx5++
done
