#!/usr/bin/env python3

import shutil
import sys 
import glob
import os
import argparse
                
parser = argparse.ArgumentParser()
parser.add_argument('src_path', action='store', type=str, help='Path to vst dll folder/* (** for subdirectories); place linvst3.so into the same folder as this script and enclose the vst dll path in quotes, for example ./linvst3convert-py "/home/user/vst/*" or ./linvst3convert-py "/home/user/vst/**" for subdirectories')
args = parser.parse_args()
files = glob.glob(args.src_path, recursive=True)

for file in files:
    if file.endswith( ".vst3" ) or file.endswith( ".VST3" ) or file.endswith( ".Vst3" ):
          sofile = file[ 0: -4 ] + ".so"
          shutil.copyfile( './linvst3.so', sofile ) 

